class Parameters_const():
    def Max_Battery(self):
        return 50
    def Transmission_range(self):
        return 500
    def Robots_not_move(self):
        return 10
    def Robots_move(self):
        return 90
